### ISSUE TITLE
script execution failure

### ISSUE THREAD

**Issue by hosseinpourziyaie** [fedddddd/h2-survival-mod#2]
im not sure if i was supposed to post it here or not. but seems script parser failure. isnt it?

```Loading fastfile estate
Loading script 'scripts/survival'
^1************** Script execution error **************
^1scripts/survival/__init__.lua:1: attempt to concatenate a nil value
^1stack traceback:
^1      scripts/survival/__init__.lua:1: in main chunk
^1****************************************************```

**Comment by alicealys** [comment]
```lua
local mapfile = io.open(scriptdir() .. "/maps/" .. game:getdvar("mapname") .. ".lua", "r")
```
I'm not sure how getting that error is possible since both scriptdir() and game:getdvar() can't return nil, did you modify the script?

**Comment by hosseinpourziyaie** [comment]
no just raw extract of og github zip

maybe its caused by my injecting methud? I use Extreme Injector v3.7.2

**Comment by alicealys** [comment]
No, I use that aswell

**Comment by hosseinpourziyaie** [comment]
so you tell me its all ok for you? we need investigate it though I never played around with lua

besides you should add game version/integrity check to avoid possible mismatches. I couldnt find any in project

**Comment by alicealys** [comment]
It works just fine for me and someone else who tried it so I have no clue what could be wrong right now

**Comment by mjkzy** [comment]
can confirm it is working on h2-mod v1.0.1 and downloading ZIP + extracting from GitHub.
