### ISSUE TITLE
Script Error in MainShop

### ISSUE THREAD

**Issue by S3RAPH-1M** [fedddddd/h2-survival-mod#4]
^3Error processing event mousemove
^3:
^3
^3stack traceback:
^3      [C]: in function 'registerAnimationState'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      (tail call): ?
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      (tail call): ?
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      (tail call): ?
^3      [string "(*stripped)"]: in function '(*stripped)'
^3
^3Error processing event mousemove
^3LUI WARNING: Anim State pool full. Collecting garbage...
^3LUI WARNING: Anim State pool full. Collecting garbage...
************** UI Script execution error **************
Error executing script function:
stack traceback:
        [C]: in field 'new'
        ...red\mods\survival\ui_scripts\survival\menus/mainshop.lua:114: in function <...red\mods\survival\ui_scripts\survival\menus/mainshop.lua:110>
****************************************************
^3Error processing event
^3:
^3attempt to index a string value
^3stack traceback:
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      (tail call): ?
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      (tail call): ?
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3
^3Error processing event
^3LUI WARNING: Anim State pool full. Collecting garbage...
^3LUI WARNING: Anim State pool full. Collecting garbage...
************** UI Script execution error **************
Error executing script function:
stack traceback:
        [C]: in field 'new'
        ...red\mods\survival\ui_scripts\survival\menus/mainshop.lua:114: in function <...red\mods\survival\ui_scripts\survival\menus/mainshop.lua:110>
****************************************************
^3Error processing event
^3:
^3attempt to index a string value
^3stack traceback:
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      (tail call): ?
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      (tail call): ?
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3
^3Error processing event
^3LUI WARNING: Anim State pool full. Collecting garbage...
^3LUI WARNING: Anim State pool full. Collecting garbage...
************** UI Script execution error **************
Error executing script function:
stack traceback:
        [C]: in field 'new'
        ...red\mods\survival\ui_scripts\survival\menus/mainshop.lua:114: in function <...red\mods\survival\ui_scripts\survival\menus/mainshop.lua:110>
****************************************************
^3Error processing event
^3:
^3attempt to index a string value
^3stack traceback:
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      (tail call): ?
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      (tail call): ?
^3      [string "(*stripped)"]: in function '(*stripped)'
^3      [string "(*stripped)"]: in function '(*stripped)'
^3
^3Error processing event
^3LUI WARNING: Anim State pool full. Collecting garbage...
^3LUI WARNING: Anim State pool full. Collecting garbage...
************** UI Script execution error **************
Error executing script function:
stack traceback:
        [C]: in field 'new'
        ...red\mods\survival\ui_scripts\survival\menus/mainshop.lua:114: in function <...red\mods\survival\ui_scripts\survival\menus/mainshop.lua:110>
****************************************************

**Comment by alicealys** [comment]
Fixed in h2-mod
