### ISSUE TITLE
Crash when trying to launch mod

### ISSUE THREAD

**Issue by Flame1211** [fedddddd/h2-survival-mod#5]
ive reinstalled the game (I have a legitimate copy of the game) and mods twice now, whenever I try to launch survival mode or Spec Ops my game just crashes and doesnt open back up

im launching with h2-mod.exe and have dragged mods into the mods folder like the instructions direct but still cant seem to launch a mod.

**Comment by Plexily** [comment]
Same thing with me. No clue what I'm doing wrong

**Comment by IcyPerkz** [comment]
ok
